global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'course_ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'course-service:8080' ]
  - job_name: 'student_ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'student-service:8081' ]
  